In [3]:
import polars as pl

In [5]:
df_pl = pl.read_csv('2019.csv')

In [8]:
df_pl.head(3)

shape: (3, 9)
┌────────────┬────────────┬───────┬────────────┬─────┬────────────┬────────────┬──────────┬────────────┐
│ Overall    ┆ Country or ┆ Score ┆ GDP per    ┆ ... ┆ Healthy    ┆ Freedom to ┆ Generosi ┆ Perception │
│ rank       ┆ region     ┆ ---   ┆ capita     ┆     ┆ life       ┆ make life  ┆ ty       ┆ s of       │
│ ---        ┆ ---        ┆ f64   ┆ ---        ┆     ┆ expectancy ┆ choices    ┆ ---      ┆ corruption │
│ i64        ┆ str        ┆       ┆ f64        ┆     ┆ ---        ┆ ---        ┆ f64      ┆ ---        │
│            ┆            ┆       ┆            ┆     ┆ f64        ┆ f64        ┆          ┆ f64        │
╞════════════╪════════════╪═══════╪════════════╪═════╪════════════╪════════════╪══════════╪════════════╡
│ 1          ┆ Finland    ┆ 7.769 ┆ 1.34       ┆ ... ┆ 0.986      ┆ 0.596      ┆ 0.153    ┆ 0.393      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ Denmark    ┆ 7.6   ┆ 1.383      ┆ ... ┆ 0.996      ┆ 0.592      ┆ 0.252    ┆ 0.41       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ Norway     ┆ 7.554 ┆ 1.488      ┆ ... ┆ 1.028      ┆ 0.603      ┆ 0.271    ┆ 0.341      │
└────────────┴────────────┴───────┴────────────┴─────┴────────────┴────────────┴──────────┴────────────┘

In [11]:
df_pl.describe()

shape: (7, 10)
┌─────┬────────────┬────────────┬──────────┬─────┬────────────┬────────────┬──────────┬────────────┐
│ des ┆ Overall    ┆ Country or ┆ Score    ┆ ... ┆ Healthy    ┆ Freedom to ┆ Generosi ┆ Perception │
│ cri ┆ rank       ┆ region     ┆ ---      ┆     ┆ life       ┆ make life  ┆ ty       ┆ s of       │
│ be  ┆ ---        ┆ ---        ┆ f64      ┆     ┆ expectancy ┆ choices    ┆ ---      ┆ corruption │
│ --- ┆ f64        ┆ str        ┆          ┆     ┆ ---        ┆ ---        ┆ f64      ┆ ---        │
│ str ┆            ┆            ┆          ┆     ┆ f64        ┆ f64        ┆          ┆ f64        │
╞═════╪════════════╪════════════╪══════════╪═════╪════════════╪════════════╪══════════╪════════════╡
│ cou ┆ 156.0      ┆ 156        ┆ 156.0    ┆ ... ┆ 156.0      ┆ 156.0      ┆ 156.0    ┆ 156.0      │
│ nt  ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ nul ┆ 0.0        ┆ 0          ┆ 0.0      ┆ ... ┆ 0.0        ┆ 0.0        ┆ 0.0      ┆ 0.0        │
│ l_c ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
│ oun ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
│ t   ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ mea ┆ 78.5       ┆ null       ┆ 5.407096 ┆ ... ┆ 0.725244   ┆ 0.392571   ┆ 0.184846 ┆ 0.110603   │
│ n   ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ std ┆ 45.177428  ┆ null       ┆ 1.11312  ┆ ... ┆ 0.242124   ┆ 0.143289   ┆ 0.095254 ┆ 0.094538   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ min ┆ 1.0        ┆ Afghanista ┆ 2.853    ┆ ... ┆ 0.0        ┆ 0.0        ┆ 0.0      ┆ 0.0        │
│     ┆            ┆ n          ┆          ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ max ┆ 156.0      ┆ Zimbabwe   ┆ 7.769    ┆ ... ┆ 1.141      ┆ 0.631      ┆ 0.566    ┆ 0.453      │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ med ┆ 78.5       ┆ null       ┆ 5.3795   ┆ ... ┆ 0.789      ┆ 0.417      ┆ 0.1775   ┆ 0.0855     │
│ ian ┆            ┆            ┆          ┆     ┆            ┆            ┆          ┆            │
└─────┴────────────┴────────────┴──────────┴─────┴────────────┴────────────┴──────────┴────────────┘

In [13]:
df_pl.columns

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [14]:
df_pl.shape

(156, 9)

In [17]:
type(df_pl)

polars.internals.dataframe.frame.DataFrame

In [19]:
dir(pl)

['ArrowError',
 'BatchedCsvReader',
 'Binary',
 'Boolean',
 'Categorical',
 'ComputeError',
 'Config',
 'DataFrame',
 'DataType',
 'Date',
 'Datetime',
 'DuplicateError',
 'Duration',
 'Expr',
 'Field',
 'Float32',
 'Float64',
 'Int16',
 'Int32',
 'Int64',
 'Int8',
 'InvalidOperationError',
 'LazyFrame',
 'List',
 'NoDataError',
 'NotFoundError',
 'Null',
 'Object',
 'PanicException',
 'PolarsDataType',
 'SQLContext',
 'SchemaError',
 'Series',
 'ShapeError',
 'StringCache',
 'Struct',
 'Time',
 'UInt16',
 'UInt32',
 'UInt64',
 'UInt8',
 'Unknown',
 'Utf8',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_html',
 'align_frames',
 'all',
 'any',
 'api',
 'apply',
 'arange',
 'arg_where',
 'argsort_by',
 'avg',
 'build_info',
 'cfg',
 'coalesce',
 'col',
 'collect_all',
 'concat',
 'concat_list',
 'concat_str',
 'convert',
 'count',
 'cov',
 'cumfold',
 'cumreduce',
 'cumsum',
 'cut',
 'datatypes',
 'datatypes_constructor',
 'date',
 'date_range',
 'datetime',
 'dependencies',
 'duration',
 'element',
 'exceptions',
 'exclude',
 'first',
 'fold',
 'format',
 'from_arrow',
 'from_dict',
 'from_dicts',
 'from_epoch',
 'from_numpy',
 'from_pandas',
 'from_records',
 'get_dummies',
 'get_idx_type',
 'groups',
 'head',
 'internals',
 'io',
 'last',
 'list',
 'lit',
 'map',
 'max',
 'mean',
 'median',
 'min',
 'n_unique',
 'ones',
 'os',
 'pearson_corr',
 'polars',
 'quantile',
 'read_avro',
 'read_csv',
 'read_csv_batched',
 'read_excel',
 'read_ipc',
 'read_ipc_schema',
 'read_json',
 'read_ndjson',
 'read_parquet',
 'read_parquet_schema',
 'read_sql',
 'reduce',
 'repeat',
 'scan_csv',
 'scan_ds',
 'scan_ipc',
 'scan_ndjson',
 'scan_parquet',
 'select',
 'show_versions',
 'spearman_rank_corr',
 'std',
 'string_cache',
 'struct',
 'sum',
 'tail',
 'threadpool_size',
 'toggle_string_cache',
 'using_string_cache',
 'utils',
 'var',
 'version',
 'warnings',
 'when',
 'wrap_df',
 'wrap_s',
 'zeros']

In [20]:
df_pl.dtypes

[polars.datatypes.Int64,
 polars.datatypes.Utf8,
 polars.datatypes.Float64,
 polars.datatypes.Float64,
 polars.datatypes.Float64,
 polars.datatypes.Float64,
 polars.datatypes.Float64,
 polars.datatypes.Float64,
 polars.datatypes.Float64]

In [21]:
dir(df_pl)

['__add__',
 '__annotations__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_accessors',
 '_comp',
 '_compare_to_non_df',
 '_compare_to_other_df',
 '_df',
 '_from_arrow',
 '_from_dict',
 '_from_dicts',
 '_from_numpy',
 '_from_pandas',
 '_from_pydf',
 '_from_records',
 '_ipython_key_completions_',
 '_pos_idx',
 '_pos_idxs',
 '_read_avro',
 '_read_csv',
 '_read_ipc',
 '_read_json',
 '_read_ndjson',
 '_read_parquet',
 '_repr_html_',
 'apply',
 'cleared',
 'clone',
 'columns',
 'describe',
 'drop',
 'drop_in_place',
 'drop_nulls',
 'dtypes',
 'estimated_size',
 'explode',
 'extend',
 'fill_nan',
 'fill_null',
 'filter',
 'find_idx_by_name',
 'fold',
 'frame_equal',
 'get_column',
 'get_columns',
 'groupby',
 'groupby_dynamic',
 'groupby_rolling',
 'hash_rows',
 'head',
 'height',
 'hstack',
 'insert_at_idx',
 'interpolate',
 'is_duplicated',
 'is_empty',
 'is_unique',
 'join',
 'join_asof',
 'lazy',
 'limit',
 'max',
 'mean',
 'median',
 'melt',
 'min',
 'n_chunks',
 'n_unique',
 'null_count',
 'partition_by',
 'pearson_corr',
 'pipe',
 'pivot',
 'product',
 'quantile',
 'rechunk',
 'rename',
 'replace',
 'replace_at_idx',
 'reverse',
 'row',
 'rows',
 'sample',
 'schema',
 'select',
 'shape',
 'shift',
 'shift_and_fill',
 'shrink_to_fit',
 'slice',
 'sort',
 'std',
 'sum',
 'tail',
 'take_every',
 'to_arrow',
 'to_dict',
 'to_dicts',
 'to_dummies',
 'to_numpy',
 'to_pandas',
 'to_series',
 'to_struct',
 'transpose',
 'unique',
 'unnest',
 'unstack',
 'upsample',
 'var',
 'vstack',
 'width',
 'with_column',
 'with_columns',
 'with_row_count',
 'write_avro',
 'write_csv',
 'write_ipc',
 'write_json',
 'write_ndjson',
 'write_parquet']

In [22]:
df_pl.to_pandas().describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

In [23]:
df_pl['Score']

shape: (156,)
Series: 'Score' [f64]
[
	7.769
	7.6
	7.554
	7.494
	7.488
	7.48
	7.343
	7.307
	7.278
	7.246
	7.228
	7.167
	...
	3.802
	3.775
	3.663
	3.597
	3.488
	3.462
	3.41
	3.38
	3.334
	3.231
	3.203
	3.083
	2.853
]

In [24]:
df_pl[0]

shape: (1, 9)
┌────────────┬────────────┬───────┬────────────┬─────┬────────────┬────────────┬──────────┬────────────┐
│ Overall    ┆ Country or ┆ Score ┆ GDP per    ┆ ... ┆ Healthy    ┆ Freedom to ┆ Generosi ┆ Perception │
│ rank       ┆ region     ┆ ---   ┆ capita     ┆     ┆ life       ┆ make life  ┆ ty       ┆ s of       │
│ ---        ┆ ---        ┆ f64   ┆ ---        ┆     ┆ expectancy ┆ choices    ┆ ---      ┆ corruption │
│ i64        ┆ str        ┆       ┆ f64        ┆     ┆ ---        ┆ ---        ┆ f64      ┆ ---        │
│            ┆            ┆       ┆            ┆     ┆ f64        ┆ f64        ┆          ┆ f64        │
╞════════════╪════════════╪═══════╪════════════╪═════╪════════════╪════════════╪══════════╪════════════╡
│ 1          ┆ Finland    ┆ 7.769 ┆ 1.34       ┆ ... ┆ 0.986      ┆ 0.596      ┆ 0.153    ┆ 0.393      │
└────────────┴────────────┴───────┴────────────┴─────┴────────────┴────────────┴──────────┴────────────┘

In [25]:
df_pl[['Score', 'Social support']]

shape: (156, 2)
┌───────┬────────────────┐
│ Score ┆ Social support │
│ ---   ┆ ---            │
│ f64   ┆ f64            │
╞═══════╪════════════════╡
│ 7.769 ┆ 1.587          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.6   ┆ 1.573          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.554 ┆ 1.582          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.494 ┆ 1.624          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...   ┆ ...            │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.231 ┆ 0.885          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.203 ┆ 0.517          │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.083 ┆ 0.0            │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2.853 ┆ 0.575          │
└───────┴────────────────┘

In [28]:
df_pl.columns

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [33]:
df_pl.select(pl.min('Generosity'))

shape: (1, 1)
┌────────────┐
│ Generosity │
│ ---        │
│ f64        │
╞════════════╡
│ 0.0        │
└────────────┘

In [40]:
df_pl.unique(subset = ['Country or region'])

shape: (156, 9)
┌────────────┬────────────┬───────┬────────────┬─────┬────────────┬────────────┬──────────┬────────────┐
│ Overall    ┆ Country or ┆ Score ┆ GDP per    ┆ ... ┆ Healthy    ┆ Freedom to ┆ Generosi ┆ Perception │
│ rank       ┆ region     ┆ ---   ┆ capita     ┆     ┆ life       ┆ make life  ┆ ty       ┆ s of       │
│ ---        ┆ ---        ┆ f64   ┆ ---        ┆     ┆ expectancy ┆ choices    ┆ ---      ┆ corruption │
│ i64        ┆ str        ┆       ┆ f64        ┆     ┆ ---        ┆ ---        ┆ f64      ┆ ---        │
│            ┆            ┆       ┆            ┆     ┆ f64        ┆ f64        ┆          ┆ f64        │
╞════════════╪════════════╪═══════╪════════════╪═════╪════════════╪════════════╪══════════╪════════════╡
│ 1          ┆ Finland    ┆ 7.769 ┆ 1.34       ┆ ... ┆ 0.986      ┆ 0.596      ┆ 0.153    ┆ 0.393      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ Denmark    ┆ 7.6   ┆ 1.383      ┆ ... ┆ 0.996      ┆ 0.592      ┆ 0.252    ┆ 0.41       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ Norway     ┆ 7.554 ┆ 1.488      ┆ ... ┆ 1.028      ┆ 0.603      ┆ 0.271    ┆ 0.341      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4          ┆ Iceland    ┆ 7.494 ┆ 1.38       ┆ ... ┆ 1.026      ┆ 0.591      ┆ 0.354    ┆ 0.118      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...        ┆ ...   ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...      ┆ ...        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 153        ┆ Tanzania   ┆ 3.231 ┆ 0.476      ┆ ... ┆ 0.499      ┆ 0.417      ┆ 0.276    ┆ 0.147      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 154        ┆ Afghanista ┆ 3.203 ┆ 0.35       ┆ ... ┆ 0.361      ┆ 0.0        ┆ 0.158    ┆ 0.025      │
│            ┆ n          ┆       ┆            ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 155        ┆ Central    ┆ 3.083 ┆ 0.026      ┆ ... ┆ 0.105      ┆ 0.225      ┆ 0.235    ┆ 0.035      │
│            ┆ African    ┆       ┆            ┆     ┆            ┆            ┆          ┆            │
│            ┆ Republic   ┆       ┆            ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 156        ┆ South      ┆ 2.853 ┆ 0.306      ┆ ... ┆ 0.295      ┆ 0.01       ┆ 0.202    ┆ 0.091      │
│            ┆ Sudan      ┆       ┆            ┆     ┆            ┆            ┆          ┆            │
└────────────┴────────────┴───────┴────────────┴─────┴────────────┴────────────┴──────────┴────────────┘

In [41]:
df_pl.select(['Score', 'Generosity'])

shape: (156, 2)
┌───────┬────────────┐
│ Score ┆ Generosity │
│ ---   ┆ ---        │
│ f64   ┆ f64        │
╞═══════╪════════════╡
│ 7.769 ┆ 0.153      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.6   ┆ 0.252      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.554 ┆ 0.271      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7.494 ┆ 0.354      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...   ┆ ...        │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.231 ┆ 0.276      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.203 ┆ 0.158      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3.083 ┆ 0.235      │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2.853 ┆ 0.202      │
└───────┴────────────┘

In [44]:
df_pl.filter(pl.col('Score') >= 7.225)

shape: (11, 9)
┌────────────┬────────────┬───────┬────────────┬─────┬────────────┬────────────┬──────────┬────────────┐
│ Overall    ┆ Country or ┆ Score ┆ GDP per    ┆ ... ┆ Healthy    ┆ Freedom to ┆ Generosi ┆ Perception │
│ rank       ┆ region     ┆ ---   ┆ capita     ┆     ┆ life       ┆ make life  ┆ ty       ┆ s of       │
│ ---        ┆ ---        ┆ f64   ┆ ---        ┆     ┆ expectancy ┆ choices    ┆ ---      ┆ corruption │
│ i64        ┆ str        ┆       ┆ f64        ┆     ┆ ---        ┆ ---        ┆ f64      ┆ ---        │
│            ┆            ┆       ┆            ┆     ┆ f64        ┆ f64        ┆          ┆ f64        │
╞════════════╪════════════╪═══════╪════════════╪═════╪════════════╪════════════╪══════════╪════════════╡
│ 1          ┆ Finland    ┆ 7.769 ┆ 1.34       ┆ ... ┆ 0.986      ┆ 0.596      ┆ 0.153    ┆ 0.393      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ Denmark    ┆ 7.6   ┆ 1.383      ┆ ... ┆ 0.996      ┆ 0.592      ┆ 0.252    ┆ 0.41       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3          ┆ Norway     ┆ 7.554 ┆ 1.488      ┆ ... ┆ 1.028      ┆ 0.603      ┆ 0.271    ┆ 0.341      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4          ┆ Iceland    ┆ 7.494 ┆ 1.38       ┆ ... ┆ 1.026      ┆ 0.591      ┆ 0.354    ┆ 0.118      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...        ┆ ...   ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...      ┆ ...        │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 8          ┆ New        ┆ 7.307 ┆ 1.303      ┆ ... ┆ 1.026      ┆ 0.585      ┆ 0.33     ┆ 0.38       │
│            ┆ Zealand    ┆       ┆            ┆     ┆            ┆            ┆          ┆            │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 9          ┆ Canada     ┆ 7.278 ┆ 1.365      ┆ ... ┆ 1.039      ┆ 0.584      ┆ 0.285    ┆ 0.308      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 10         ┆ Austria    ┆ 7.246 ┆ 1.376      ┆ ... ┆ 1.016      ┆ 0.532      ┆ 0.244    ┆ 0.226      │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 11         ┆ Australia  ┆ 7.228 ┆ 1.372      ┆ ... ┆ 1.036      ┆ 0.557      ┆ 0.332    ┆ 0.29       │
└────────────┴────────────┴───────┴────────────┴─────┴────────────┴────────────┴──────────┴────────────┘

In [49]:
import seaborn as sns

In [50]:
df = sns.load_dataset('iris')

In [51]:
df = pl.DataFrame(df)

In [52]:
type(df)

polars.internals.dataframe.frame.DataFrame

In [53]:
df

shape: (150, 5)
┌──────────────┬─────────────┬──────────────┬─────────────┬───────────┐
│ sepal_length ┆ sepal_width ┆ petal_length ┆ petal_width ┆ species   │
│ ---          ┆ ---         ┆ ---          ┆ ---         ┆ ---       │
│ f64          ┆ f64         ┆ f64          ┆ f64         ┆ str       │
╞══════════════╪═════════════╪══════════════╪═════════════╪═══════════╡
│ 5.1          ┆ 3.5         ┆ 1.4          ┆ 0.2         ┆ setosa    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4.9          ┆ 3.0         ┆ 1.4          ┆ 0.2         ┆ setosa    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4.7          ┆ 3.2         ┆ 1.3          ┆ 0.2         ┆ setosa    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 4.6          ┆ 3.1         ┆ 1.5          ┆ 0.2         ┆ setosa    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...          ┆ ...         ┆ ...          ┆ ...         ┆ ...       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 6.3          ┆ 2.5         ┆ 5.0          ┆ 1.9         ┆ virginica │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 6.5          ┆ 3.0         ┆ 5.2          ┆ 2.0         ┆ virginica │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 6.2          ┆ 3.4         ┆ 5.4          ┆ 2.3         ┆ virginica │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 5.9          ┆ 3.0         ┆ 5.1          ┆ 1.8         ┆ virginica │
└──────────────┴─────────────┴──────────────┴─────────────┴───────────┘

In [57]:
df.groupby('species').agg(pl.col('petal_width'))

shape: (3, 2)
┌────────────┬─────────────────────┐
│ species    ┆ petal_width         │
│ ---        ┆ ---                 │
│ str        ┆ list[f64]           │
╞════════════╪═════════════════════╡
│ versicolor ┆ [1.4, 1.5, ... 1.3] │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ virginica  ┆ [2.5, 1.9, ... 1.8] │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ setosa     ┆ [0.2, 0.2, ... 0.2] │
└────────────┴─────────────────────┘

In [58]:
df.select([pl.col('species') == 'virginica'])

shape: (150, 1)
┌─────────┐
│ species │
│ ---     │
│ bool    │
╞═════════╡
│ false   │
├╌╌╌╌╌╌╌╌╌┤
│ false   │
├╌╌╌╌╌╌╌╌╌┤
│ false   │
├╌╌╌╌╌╌╌╌╌┤
│ false   │
├╌╌╌╌╌╌╌╌╌┤
│ ...     │
├╌╌╌╌╌╌╌╌╌┤
│ true    │
├╌╌╌╌╌╌╌╌╌┤
│ true    │
├╌╌╌╌╌╌╌╌╌┤
│ true    │
├╌╌╌╌╌╌╌╌╌┤
│ true    │
└─────────┘

In [59]:
pl.col('species')